server {
    listen 80;

    location /api/customers {
        proxy_pass http://customer-service:8081;
    }

    location /api/reviews {
        proxy_pass http://review-service:8082;
    }

    location /api/ {
        proxy_pass http://booking-service:8080;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}
