spring.application.name=Booking-Service
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/bookingDb?createDatabaseIfNotExist=true
spring.datasource.username=user
spring.datasource.password=123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

customer.service.url=http://${CUSTOMER_SERVICE_HOST:localhost}:8081