spring.application.name=Booking-Service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://{DB_HOST:localhost}:3306/bookingDb?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

customer.service.url=${CUSTOMER_SERVICE_URL:http://${CUSTOMER_SERVICE_HOST:localhost}:8081}
